In [49]:
import joblib

model_under_attack = joblib.load("../model1")
# model_under_attack.(leo_df_X, leo_df_y) 

print(model_under_attack)

RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, n_jobs=-1)


/Users/reddy/miniconda3/lib/python3.10/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.3.0 when using version 1.3.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/reddy/miniconda3/lib/python3.10/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.3.0 when using version 1.3.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [3]:
dir(model_under_attack)
pass

In [37]:
print(model_under_attack._check_feature_names)
print(model_under_attack._check_n_features)
print(model_under_attack.get_metadata_routing)

inpu = [i for i in range(3000)]
inpu2 = [i for i in range(0,3000)]
inpu2.reverse()

import numpy
print(numpy.array([inpu, inpu2]).shape)
# input feature = 3000x1
print(model_under_attack.predict([inpu, inpu2]))
print(model_under_attack.predict([inpu, inpu2]).shape)
print(model_under_attack.predict([inpu2]).shape)

<bound method BaseEstimator._check_feature_names of RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, n_jobs=-1)>
<bound method BaseEstimator._check_n_features of RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, n_jobs=-1)>
<bound method _MetadataRequester.get_metadata_routing of RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, n_jobs=-1)>
(2, 3000)
[1 1]
(2,)
(1,)


In [50]:
import numpy as np
np.set_printoptions(threshold=np.inf)
print("Before Attack: ")
print("Top 5 features")
print(model_under_attack.feature_importances_.argsort()[-5:][::-1])



from numpy import random

x=[random.uniform(10000, size=(3000)) for i in range(200)]

# Before attack:
print(model_under_attack.predict(x))

for i in range(100):
    x[i][13] = random.uniform(1, 1000)
    x[i][20] = random.uniform(1000, 10000)
    x[i][37] = random.uniform(1000, 10000)
    x[i][92] = random.uniform(1000, 10000)
    x[i][916] = random.uniform(1000, 10000)

print("After Attack: ")
print("Top 5 features")
print(model_under_attack.feature_importances_.argsort()[-5:][::-1])
model_under_attack.fit(x[:100], [2 for i in range(100)])
model_under_attack.predict(x[100:])

Before Attack: 
[ 13  37  92 916  20]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
After Attack: 
[ 13  37  92 916  20]


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [51]:
import joblib

model_under_attack2 = joblib.load("../model11")
# model_under_attack.(leo_df_X, leo_df_y) 

# print(model_under_attack2)